[providers]
default = "google"

[openai]
model = "gpt-4-0125-preview"
api_key_env = "OPENAI_API_KEY"
options = ["gpt-4-0125-preview"]

[google]
model = "gemini-pro"
api_key_env = "GOOGLE_API_KEY"
options = ["gemini-pro"]
